# Generated by Django 3.2.25 on 2026-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('sin_active', models.SmallIntegerField(db_column='sin_active', default=1)),
                ('fk_created_by', models.IntegerField(blank=True, db_column='fk_created_by', null=True)),
                ('dat_created', models.DateTimeField(blank=True, db_column='dat_created', null=True)),
                ('fk_modified_by', models.IntegerField(blank=True, db_column='fk_modified_by', null=True)),
                ('dat_modified', models.DateTimeField(blank=True, db_column='dat_modified', null=True)),
                ('pk_user_id', models.AutoField(db_column='pk_user_id', primary_key=True, serialize=False)),
                ('vhr_user_name', models.CharField(db_column='vhr_user_name', max_length=100, unique=True)),
                ('vhr_display_name', models.CharField(blank=True, db_column='vhr_display_name', default='', max_length=120)),
                ('vhr_password', models.CharField(blank=True, db_column='vhr_password', default='', max_length=255)),
                ('sin_user_type', models.SmallIntegerField(db_column='sin_user_type', default=3)),
                ('fk_location_id', models.IntegerField(blank=True, db_column='fk_location_id', null=True)),
                ('dat_last_login', models.DateTimeField(blank=True, db_column='dat_last_login', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='TbmItem',
            fields=[
                ('sin_active', models.SmallIntegerField(db_column='sin_active', default=1)),
                ('fk_created_by', models.IntegerField(blank=True, db_column='fk_created_by', null=True)),
                ('dat_created', models.DateTimeField(blank=True, db_column='dat_created', null=True)),
                ('fk_modified_by', models.IntegerField(blank=True, db_column='fk_modified_by', null=True)),
                ('dat_modified', models.DateTimeField(blank=True, db_column='dat_modified', null=True)),
                ('pk_item_id', models.AutoField(db_column='pk_item_id', primary_key=True, serialize=False)),
                ('vhr_item_code', models.CharField(db_column='vhr_item_code', max_length=30, unique=True)),
                ('vhr_item_name', models.CharField(db_column='vhr_item_name', max_length=180)),
                ('vhr_category', models.CharField(blank=True, db_column='vhr_category', default='', max_length=80)),
                ('vhr_unit', models.CharField(blank=True, db_column='vhr_unit', default='', max_length=20)),
                ('dbl_reorder_level', models.DecimalField(db_column='dbl_reorder_level', decimal_places=3, default=0, max_digits=14)),
                ('dbl_standard_cost', models.DecimalField(db_column='dbl_standard_cost', decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'tbm_item',
            },
        ),
    ]
