# Generated by Django 3.2.25 on 2026-06-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='codename',
            new_name='strCodename',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='description',
            new_name='strDescription',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='strName',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='created_at',
            new_name='dtCreatedAt',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='updated_at',
            new_name='dtUpdatedAt',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='listPermissions',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='strDescription',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='strName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='dtCreatedAt',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='strAvatar',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='strEmail',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='strName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='role_name',
            new_name='strRoleName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='strStatus',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='strUsername',
        ),
    ]
