# Generated by Django 3.2.25 on 2026-06-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20260611_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strName', models.CharField(max_length=255, unique=True)),
                ('strDescription', models.TextField(blank=True, null=True)),
                ('objCreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='rbac.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCode', models.CharField(max_length=50, unique=True)),
                ('strName', models.CharField(max_length=255)),
                ('strUnit', models.CharField(max_length=50)),
                ('intReorderLevel', models.IntegerField(default=0)),
                ('strStatus', models.CharField(default='Active', max_length=20)),
                ('strDescription', models.TextField(blank=True, null=True)),
                ('intCurrentStock', models.IntegerField(default=0)),
                ('floaPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('strColor', models.CharField(default='#e0e7ff', max_length=20)),
                ('strTextColor', models.CharField(default='#4f46e5', max_length=20)),
                ('strIcon', models.CharField(default='file-text', max_length=50)),
                ('objCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rbac.category')),
                ('objCreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='rbac.userprofile')),
            ],
        ),
    ]
