# Generated by Django 3.2.25 on 2026-06-13 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCode', models.CharField(max_length=50, unique=True)),
                ('strName', models.CharField(max_length=255)),
                ('strEmail', models.EmailField(max_length=254)),
                ('strPhone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCode', models.CharField(max_length=50)),
                ('strName', models.CharField(max_length=255)),
                ('objSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rbac.supplier')),
            ],
        ),
    ]
