# Generated by Django 3.2.25 on 2026-06-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_supplier_supplieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='objCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_items', to='rbac.category'),
        ),
    ]
