# Generated by Django 3.2.25 on 2026-06-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_supplieritem_objcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCode', models.CharField(max_length=50, unique=True)),
                ('strName', models.CharField(max_length=255)),
                ('strLocation', models.CharField(max_length=255)),
                ('strContact', models.CharField(max_length=50)),
            ],
        ),
    ]
