# Generated by Django 3.2.25 on 2026-06-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='objBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rbac.branch'),
        ),
    ]
