# Generated by Django 3.2.25 on 2026-06-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_userprofile_objbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='strManagerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='strManagerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='strManagerPhone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
