# Generated by Django 3.2.25 on 2026-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20260614_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strPassword',
            field=models.CharField(default='pbkdf2_sha256$260000$C1zTCIuRZRMswUiHrsFds9$IWTahia7wl5VazKSMVKAyrKys+gkgDb60cc4OMKJpuo=', max_length=255),
        ),
    ]
