# Generated by Django 3.2.25 on 2026-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_userprofile_strpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='floaPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
