# Generated by Django 3.2.25 on 2026-06-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_supplieritem_floaprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strPurchaseNo', models.CharField(max_length=50, unique=True)),
                ('strSupplier', models.TextField()),
                ('strInvoiceDate', models.DateField()),
                ('strLocation', models.CharField(default='Central Office', max_length=100)),
                ('strStatus', models.CharField(default='Draft', max_length=20)),
                ('floaSubtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('floaVat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('floaTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('dtUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCode', models.CharField(max_length=50)),
                ('strName', models.CharField(max_length=255)),
                ('strCategory', models.CharField(max_length=100)),
                ('strUnit', models.CharField(max_length=50)),
                ('intQty', models.IntegerField(default=1)),
                ('floaPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('strDescription', models.TextField(blank=True, null=True)),
                ('strColor', models.CharField(default='#e0e7ff', max_length=20)),
                ('strTextColor', models.CharField(default='#4f46e5', max_length=20)),
                ('strIcon', models.CharField(default='file-text', max_length=50)),
                ('objPurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rbac.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='CentralStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intCurrentStock', models.IntegerField(default=0)),
                ('dtLastUpdated', models.DateTimeField(auto_now=True)),
                ('objItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='central_stock', to='rbac.item')),
            ],
        ),
    ]
