# Generated by Django 3.2.25 on 2026-06-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_centralstock_purchase_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strRequisitionNo', models.CharField(blank=True, max_length=50, unique=True)),
                ('strBranchName', models.CharField(blank=True, default='', max_length=255)),
                ('strRequiredByDate', models.DateField()),
                ('strRemarks', models.CharField(blank=True, default='', max_length=500)),
                ('strStatus', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Received', 'Received')], default='Draft', max_length=20)),
                ('floaTotalValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('strRejectReason', models.CharField(blank=True, default='', max_length=1000)),
                ('strDecidedBy', models.CharField(blank=True, default='', max_length=255)),
                ('dtDecidedAt', models.DateTimeField(blank=True, null=True)),
                ('strAssignedToName', models.CharField(blank=True, default='', max_length=255)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('dtUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dtLastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strMovementNo', models.CharField(blank=True, max_length=50, unique=True)),
                ('strSource', models.CharField(default='Central Office', max_length=100)),
                ('strDestination', models.CharField(max_length=255)),
                ('dtDispatchDate', models.DateTimeField(auto_now_add=True)),
                ('strReceiveStatus', models.CharField(default='Pending', max_length=20)),
                ('strApprovedBy', models.CharField(max_length=255)),
                ('objRequisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='rbac.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strItemCode', models.CharField(max_length=50)),
                ('strName', models.CharField(max_length=255)),
                ('strDescription', models.TextField(blank=True, default='')),
                ('strUnit', models.CharField(default='Nos', max_length=50)),
                ('floaPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('intQty', models.IntegerField(default=1)),
                ('intApprovedQty', models.IntegerField(default=0)),
                ('intOnHand', models.IntegerField(default=0)),
                ('strColor', models.CharField(default='#e0e7ff', max_length=20)),
                ('strTextColor', models.CharField(default='#4f46e5', max_length=20)),
                ('strIcon', models.CharField(default='file-text', max_length=50)),
                ('objRequisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrItems', to='rbac.requisition')),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='objAssignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to='rbac.userprofile'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='objBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='rbac.branch'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='objCreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='rbac.userprofile'),
        ),
    ]
