# Generated by Django 6.0.6 on 2026-06-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_auto_20260621_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strLocation', models.CharField(max_length=255)),
                ('intQuantity', models.IntegerField(default=0)),
                ('dtLastUpdated', models.DateTimeField(auto_now=True)),
                ('objItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance_lines', to='rbac.item')),
            ],
            options={
                'unique_together': {('objItem', 'strLocation')},
            },
        ),
    ]
